version: '3.2'
services:
  rabbit:
    image: rabbitmq:3-management
    container_name: rabbit
    hostname: rabbit
    networks:
      - coinbase
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: unless-stopped
  influxdb:
    image: influxdb:1.7
    container_name: influxdb
    networks:
      - coinbase
    ports:
      - "8086:8086"
    volumes:
     - type: bind
       source: ./mnt/influxdb
       target: /var/lib/influxdb
    environment:
      - INFLUXDB_DB=coinbase
    restart: unless-stopped
  grafana:
    build: ./grafana
    container_name: coinbase_grafana
    networks:
      - coinbase
    ports:
      - "3000:3000"
  db_validator:
    build: ./python_influx
    image: python_influx
    container_name: db_validator
    networks:
      - coinbase
    environment:
      - PYTHONUNBUFFERED=0
    restart: unless-stopped
    command: python3 -u validator.py
    depends_on:
      - influxdb
  websocket:
    image: python_influx
    container_name: websocket
    networks:
      - coinbase
    environment:
      - PYTHONUNBUFFERED=0
    restart: unless-stopped
    command: python3 -u websocket.py
    depends_on:
      - rabbit
  websocket_to_trade:
    image: python_influx
    container_name: websocket_to_trade
    networks:
      - coinbase
    environment:
      - PYTHONUNBUFFERED=0
    restart: unless-stopped
    command: python3 -u websocket_to_trade.py
    depends_on:
      - rabbit
  trades_to_influx:
    image: python_influx
    container_name: trades_to_influx
    networks:
      - coinbase
    environment:
      - PYTHONUNBUFFERED=0
    restart: unless-stopped
    command: python3 -u trades_to_influx.py
    depends_on:
      - rabbit
      - influxdb
  trades_to_timescale:
    image: python_influx
    container_name: trades_to_timescale
    networks:
      - coinbase
    environment:
      - PYTHONUNBUFFERED=0
    restart: unless-stopped
    command: python3 -u trades_to_timescale.py
    depends_on:
      - rabbit
      - timescale
  timescale:
    image: timescale/timescaledb:latest-pg11
    container_name: timescaledb
    restart: unless-stopped
    networks:
      - coinbase
    ports:
      - "5432:5432"
    volumes:
     - type: bind
       source: ./mnt/timescaledb
       target: /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=bitcoin

networks:
  coinbase:
